import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,readFile,readdir} from 'node:fs/promises';
import {build} from 'esbuild';
import {Miniflare} from 'miniflare';

test('class administration, assignment ownership and password changes enforce account boundaries',async()=>{
 await mkdir('.sites-runtime/tests',{recursive:true});const path='.sites-runtime/tests/account-management.mjs';
 await build({entryPoints:['tests/app-worker.ts'],outfile:path,bundle:true,format:'esm',platform:'node',external:['node:*','cloudflare:workers'],banner:{js:'import {createRequire} from "node:module";const require=createRequire("/worker.js");'},logLevel:'silent'});
 const mf=new Miniflare({modules:[{type:'ESModule',path,contents:await readFile(path,'utf8')}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB','STORAGE_DB'],r2Buckets:['BUCKET'],bindings:{STORAGE_EPOCH:'test-generation',BETTER_AUTH_URL:'https://test.local',BETTER_AUTH_SECRET:'test-secret-with-at-least-32-characters',CLASS_INVITE_CODE:'invite'}});
 try{
  const db=await mf.getD1Database('DB');for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const sql of (await readFile('drizzle/'+f,'utf8')).split('--> statement-breakpoint').filter(s=>s.trim()))await db.prepare(sql).run();
  const storage=await mf.getD1Database('STORAGE_DB'),bucket=await mf.getR2Bucket('BUCKET');
  for(const sql of (await readFile('deployment/storage/0000_storage.sql','utf8')).split('--> statement-breakpoint').filter(s=>s.trim()))await storage.prepare(sql).run();
  await storage.prepare("UPDATE storage_budget SET enabled=1,epoch='test-generation' WHERE id=1").run();
  const call=(path,method='GET',cookie='',body,origin='https://test.local')=>mf.dispatchFetch('https://test.local'+path,{method,headers:{origin,'content-type':'application/json',cookie,'cf-connecting-ip':'192.0.2.44'},body:body===undefined?undefined:JSON.stringify(body)});
  const cookie=r=>r.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
  async function signup(username){const r=await call('/api/auth/sign-up/email','POST','',{username,name:username,email:'pending@example.invalid',password:'original-password-2026',inviteCode:'invite'});assert.equal(r.status,200);return {cookie:cookie(r),user:(await r.json()).user};}
  const owner=await signup('task_owner'),member=await signup('task_member'),admin=await signup('class_admin');
  await db.prepare("UPDATE user SET role='admin' WHERE id=?").bind(admin.user.id).run();
  const draft={subject:'数学',title:'課題',description:'',deadline:'2026-10-01T09:00:00.000Z'};
  const made=await call('/api/app/assignments','POST',owner.cookie,draft);assert.equal(made.status,201);const id=(await made.json()).id,url='/api/app/assignments/'+id;
  assert.equal((await call(url,'PATCH',member.cookie,{...draft,title:'他人の変更'})).status,403);
  assert.equal((await call(url,'DELETE',member.cookie)).status,403);
  assert.equal((await call(url,'PATCH',admin.cookie,{...draft,title:'管理者の変更'})).status,200);
  assert.equal((await db.prepare('SELECT created_by FROM assignments WHERE id=?').bind(id).first()).created_by,owner.user.id);
  assert.equal((await call(url,'PATCH',admin.cookie,{...draft,created_by:admin.user.id})).status,400);
  assert.equal((await call('/api/app/class','PUT',member.cookie,{name:'無断変更'})).status,403);
  assert.equal((await call('/api/app/class','PUT',admin.cookie,{name:'   '})).status,400);
  assert.equal((await call('/api/app/class','PUT',admin.cookie,{name:'物性論のチーム'})).status,200);
  assert.equal((await (await call('/api/app','GET',member.cookie)).json()).className,'物性論のチーム');
  const invite=await call('/api/admin/invitation','POST',admin.cookie,{className:'演習クラス'});assert.equal(invite.status,200);assert.equal((await invite.json()).className,'演習クラス');
  assert.equal((await call('/api/app/profile','PUT',member.cookie,{name:'表示名を変更'})).status,200);
  assert.equal((await call('/api/app/profile','PUT',member.cookie,{name:'名前',role:'admin'})).status,400);
  assert.equal((await (await call('/api/app','GET',member.cookie)).json()).user.name,'表示名を変更');
  assert.equal((await call(url+'/submission','PUT',member.cookie,{submitted:true,userId:owner.user.id})).status,400);
  assert.equal((await call(url+'/submission','PUT',member.cookie,{submitted:true})).status,200);
  await call(url+'/settings','PUT',member.cookie,{importance:3,plannedFor:null});
  await call('/api/reminders/'+id,'PUT',member.cookie,{customAt:'2026-12-01T00:00:00.000Z',deadlineEnabled:true});
  await db.prepare("UPDATE user SET classId='outside' WHERE id=?").bind(admin.user.id).run();
  assert.equal((await call(url,'DELETE',admin.cookie)).status,404);
  await db.prepare("UPDATE user SET classId='prototype' WHERE id=?").bind(admin.user.id).run();
  const pdf=await readFile('tests/fixtures/connectivity.pdf');
  const uploaded=await mf.dispatchFetch('https://test.local/api/files/'+id,{method:'POST',headers:{origin:'https://test.local',cookie:admin.cookie,'x-file-name':'test.pdf'},body:pdf});assert.equal(uploaded.status,201,'administrator can maintain attachments');
  const fileId=(await uploaded.json()).id;
  assert.equal((await mf.dispatchFetch('https://test.local/api/files/'+id+'/'+fileId,{headers:{cookie:member.cookie}})).status,200);
  const reserved=(await storage.prepare('SELECT reserved_bytes FROM storage_budget').first()).reserved_bytes;
  await storage.prepare('UPDATE storage_budget SET enabled=0 WHERE id=1').run();
  assert.equal((await call(url,'DELETE',admin.cookie)).status,503,'deletion never bypasses the cost gate');
  assert.equal((await storage.prepare('SELECT reserved_bytes FROM storage_budget').first()).reserved_bytes,reserved);
  assert.equal((await bucket.list()).objects.length,1);
  assert.equal((await db.prepare('SELECT count(*) AS n FROM submissions').first()).n,1);
  await storage.prepare('UPDATE storage_budget SET enabled=1 WHERE id=1').run();
  assert.equal((await call(url,'DELETE',owner.cookie)).status,200);
  assert.equal((await bucket.list()).objects.length,0);assert.equal((await storage.prepare('SELECT reserved_bytes FROM storage_budget').first()).reserved_bytes,0);
  for(const table of ['assignments','assignment_settings','submissions','reminder_settings','reminder_events','notifications','notification_events'])assert.equal((await db.prepare(`SELECT count(*) AS n FROM ${table}`).first()).n,0);
  const other=(await (await call('/api/app/assignments','POST',owner.cookie,draft)).json()).id;
  assert.equal((await call('/api/app/assignments/'+other,'DELETE',admin.cookie)).status,200);
  await db.prepare("UPDATE user SET role='member' WHERE id=?").bind(admin.user.id).run();
  assert.equal((await call('/api/app/class','PUT',admin.cookie,{name:'変更'})).status,403);
  const second=await call('/api/auth/sign-in/username','POST','',{username:'task_member',password:'original-password-2026'});assert.equal(second.status,200);const secondCookie=cookie(second);
  const sessions=await db.prepare('SELECT id FROM session WHERE userId=?').bind(member.user.id).all();
  for(const s of sessions.results)await db.prepare('INSERT INTO subscriptions(id,label,endpoint,p256dh,auth,updated_at,user_id,session_id,enabled) VALUES(?,?,?,?,?,?,?,?,1)').bind(s.id,'test','https://web.push.apple.com/'+s.id,'test','test',new Date().toISOString(),member.user.id,s.id).run();
  const change={currentPassword:'original-password-2026',newPassword:'replacement-password-2026',revokeOtherSessions:false};
  assert.equal((await call('/api/auth/change-password','POST','',change)).status,401);
  assert.equal((await call('/api/auth/change-password','POST',member.cookie,change,'https://outside.invalid')).status,403);
  assert.equal((await call('/api/auth/change-password','POST',member.cookie,{...change,currentPassword:'incorrect-password'})).status,400);
  const changed=await call('/api/auth/change-password','POST',member.cookie,change);assert.equal(changed.status,200);const newCookie=cookie(changed);
  assert.equal((await call('/api/app','GET',secondCookie)).status,401,'changing password always revokes other sessions');
  assert.equal((await db.prepare('SELECT count(*) AS n FROM subscriptions WHERE enabled=1 OR user_id IS NOT NULL').first()).n,0,'revoked sessions also relinquish device ownership');
  assert.equal((await call('/api/app','GET',newCookie)).status,200);
  assert.notEqual((await call('/api/auth/sign-in/username','POST','',{username:'task_member',password:'original-password-2026'})).status,200);
  assert.equal((await call('/api/auth/sign-in/username','POST','',{username:'task_member',password:change.newPassword})).status,200);
 }finally{await mf.dispose();}
});
